// Topics + Word lists in a separate file for easy updates
window.TOPICS = [
  'Animals','Countries','Fruits','Cities','Colors','Sports','Vehicles',
  'Occupations','Things in a kitchen','Movies','TV Shows','Cartoons',
  'Superheroes','Foods','Desserts','Body parts','School subjects','Toys',
  'Games','Stores','Restaurants','Holidays','Tools','Weather','Emotions'
];

window.WORD_LISTS = {
  'Animals': ['aardvark','alligator','alpaca','ant','anteater','antelope','ape','armadillo','baboon','badger','barn owl','bat','bear','beaver','bee','beetle','bird','bison','black bear','blue whale','boar','brown bear','buffalo','bull','butterfly','camel','cat','caterpillar','cheetah','chicken','chimpanzee','chipmunk','cobra','cow','coyote','crab','crane','crocodile','crow','deer','dog','dolphin','donkey','dove','duck','eagle','eel','elephant','elk','emu','falcon','ferret','fire ant','fish','flamingo','fly','fox','frog','fruit bat','gazelle','giraffe','goat','goose','gorilla','grasshopper','gray wolf','grizzly bear','hamster','hawk','hedgehog','hippo','honey bee','horse','hummingbird','hyena','iguana','jackal','jaguar','jellyfish','kangaroo','killer whale','koala','ladybug','lamb','leopard','lion','lizard','llama','lobster','lynx','monkey','moose','mouse','mule','newt','octopus','opossum','ostrich','otter','owl','ox','panda','panther','parrot','peacock','pelican','penguin','pig','pigeon','polar bear','porcupine','quail','rabbit','raccoon','rat','raven','red fox','rhinoceros','robin','sea lion','seahorse','seal','shark','sheep','skunk','sloth','snail','snake','spider','squirrel','starfish','swan','tiger','turkey','turtle','unicorn','vampire bat','vulture','walrus','wasp','whale','white shark','wolf','woodpecker','worm','yak','zebra'],
  'Countries': ['afghanistan','albania','algeria','andorra','angola','argentina','armenia','australia','austria','azerbaijan','bahamas','bahrain','bangladesh','barbados','belarus','belgium','belize','benin','bhutan','bolivia','bosnia','botswana','brazil','brunei','bulgaria','burkina faso','burundi','cambodia','cameroon','canada','cape verde','chad','chile','china','colombia','comoros','congo','costa rica','croatia','cuba','cyprus','czech republic','democratic republic of congo','denmark','djibouti','dominica','dominican republic','east timor','ecuador','egypt','el salvador','equatorial guinea','eritrea','estonia','ethiopia','fiji','finland','france','gabon','gambia','georgia','germany','ghana','greece','grenada','guatemala','guinea','guinea bissau','guyana','haiti','honduras','hungary','iceland','india','indonesia','iran','iraq','ireland','israel','italy','ivory coast','jamaica','japan','jordan','kazakhstan','kenya','kiribati','kuwait','kyrgyzstan','laos','latvia','lebanon','lesotho','liberia','libya','liechtenstein','lithuania','luxembourg','macedonia','madagascar','malawi','malaysia','maldives','mali','malta','marshall islands','mauritania','mauritius','mexico','micronesia','moldova','monaco','mongolia','montenegro','morocco','mozambique','myanmar','namibia','nauru','nepal','netherlands','new zealand','nicaragua','niger','nigeria','north korea','norway','oman','pakistan','palau','panama','papua new guinea','paraguay','peru','philippines','poland','portugal','qatar','romania','russia','rwanda','saint lucia','samoa','san marino','saudi arabia','senegal','serbia','seychelles','sierra leone','singapore','slovakia','slovenia','solomon islands','somalia','south africa','south korea','south sudan','spain','sri lanka','sudan','suriname','swaziland','sweden','switzerland','syria','taiwan','tajikistan','tanzania','thailand','togo','tonga','trinidad and tobago','tunisia','turkey','turkmenistan','tuvalu','uganda','ukraine','united arab emirates','united kingdom','united states','uruguay','uzbekistan','vanuatu','vatican city','venezuela','vietnam','wales','yemen','zambia','zimbabwe'],
  'Fruits': ['acai','apple','apricot','avocado','banana','blackberry','blackcurrant','blueberry','boysenberry','breadfruit','cantaloupe','cherry','clementine','coconut','cranberry','currant','date','dragonfruit','durian','elderberry','fig','gooseberry','grape','grapefruit','guava','honeydew','huckleberry','jackfruit','kiwi','kumquat','lemon','lime','lingonberry','lychee','mandarin','mango','melon','mulberry','nectarine','orange','papaya','passionfruit','peach','pear','persimmon','pineapple','plum','pomegranate','pomelo','prickly pear','quince','rambutan','raspberry','starfruit','strawberry','tangerine','tomato','ugli fruit','vanilla','watermelon','ximenia','yuzu','zucchini'],
  'Colors': ['amber','aqua','aquamarine','azure','beige','black','blue','bronze','brown','burgundy','burnt orange','chartreuse','coral','crimson','cyan','dark blue','emerald','forest green','fuchsia','gold','gray','green','hot pink','indigo','ivory','jade','khaki','lavender','lemon','lime','magenta','maroon','mint','navy','olive','orange','peach','pink','plum','purple','red','rose','ruby','salmon','scarlet','silver','tan','teal','turquoise','ultramarine','violet','white','yellow','zinc'],
  'Cities': ['atlanta','amsterdam','austin','baghdad','baltimore','bangkok','barcelona','beijing','berlin','birmingham','bogota','boston','brussels','budapest','buenos aires','cairo','calcutta','cape town','caracas','chicago','cologne','copenhagen','dallas','delhi','denver','detroit','dublin','dubai','edinburgh','florence','frankfurt','geneva','glasgow','hamburg','helsinki','hong kong','houston','istanbul','jakarta','jerusalem','johannesburg','kansas city','kiev','kuala lumpur','kyoto','las vegas','lima','lisbon','london','los angeles','lyon','madrid','manchester','manila','marseille','melbourne','mexico city','miami','milan','montreal','moscow','mumbai','munich','nairobi','naples','new delhi','new york','nice','oslo','ottawa','paris','philadelphia','phoenix','prague','quebec','rio de janeiro','rome','saint petersburg','san francisco','santiago','sao paulo','seattle','seoul','shanghai','singapore','stockholm','sydney','tehran','tokyo','toronto','tunis','vancouver','venice','vienna','warsaw','washington','yokohama','zurich'],
  'Sports': ['archery','athletics','badminton','baseball','basketball','biathlon','bobsled','bowling','boxing','canoeing','cricket','curling','cycling','darts','diving','equestrian','fencing','football','golf','gymnastics','handball','hockey','judo','karate','kayaking','lacrosse','marathon','martial arts','netball','polo','powerlifting','quidditch','racquetball','rowing','rugby','running','sailing','skiing','snowboarding','soccer','softball','squash','surfing','swimming','table tennis','taekwondo','tennis','track and field','triathlon','ultimate frisbee','volleyball','water polo','weightlifting','wrestling','yoga'],
  'Vehicles': ['airplane','ambulance','bicycle','boat','bus','car','canoe','drone','ferry','helicopter','jet','kayak','limousine','motorcycle','plane','rocket','scooter','ship','submarine','taxi','train','truck','van','yacht'],
  'Occupations': ['actor','baker','chef','doctor','engineer','farmer','guard','nurse','pilot','teacher','writer'],
  'Things in a kitchen': ['blender','bowl','cup','dish','fork','glass','kettle','knife','ladle','mug','oven','pan','plate','pot','spoon','toaster'],
  'Movies': ['avatar','batman','cars','dumbo','elf','frozen','gladiator','hulk','inception','jaws','kramer','lego movie','matrix','nemo','pirates','rocky','superman','titanic','up','wall-e','x-men'],
  'TV Shows': ['friends','seinfeld','the office','breaking bad','lost','game of thrones','stranger things','the simpsons','family guy','south park'],
  'Cartoons': ['mickey mouse','bugs bunny','tom and jerry','scooby doo','spongebob','pokemon','dragon ball','naruto','sailor moon','teenage mutant ninja turtles'],
  'Superheroes': ['batman','superman','spiderman','wonder woman','iron man','captain america','hulk','thor','flash','green lantern','aquaman','wolverine','deadpool','black widow','ant-man'],
  'Foods': ['apple','bread','cheese','donut','egg','fish','garlic','ham','ice cream','jam','kale','lobster','meat','nuts','onion','pasta','quinoa','rice','soup','toast','udon','vanilla','waffle','yogurt','ziti'],
  'Desserts': ['cake','cookies','pie','ice cream','pudding','brownie','donut','candy','chocolate','marshmallow','fudge','cupcake','tart','mousse','sorbet'],
  'Body parts': ['ankle','arm','back','chest','ear','elbow','eye','face','foot','hand','head','knee','leg','mouth','neck','nose','shoulder','thumb','toe','waist'],
  'School subjects': ['art','biology','chemistry','drama','english','french','geography','history','music','physics','science','math','literature','psychology','sociology'],
  'Toys': ['ball','doll','blocks','puzzle','teddy bear','car','train','airplane','robot','action figure','board game','video game','kite','yo-yo','frisbee'],
  'Games': ['chess','checkers','monopoly','scrabble','poker','blackjack','bingo','solitaire','hide and seek','tag','hopscotch','jump rope','video games','board games','card games'],
  'Stores': ['grocery store','pharmacy','bookstore','clothing store','hardware store','pet store','toy store','electronics store','department store','convenience store'],
  'Restaurants': ['mcdonalds','burger king','subway','pizza hut','kfc','taco bell','chinese restaurant','italian restaurant','mexican restaurant','fast food','diner','cafe'],
  'Holidays': ['christmas','thanksgiving','halloween','easter','valentines day','new years','independence day','memorial day','labor day','mothers day','fathers day','birthday'],
  'Tools': ['hammer','screwdriver','wrench','saw','drill','pliers','measuring tape','level','chisel','file','sandpaper','nail','screw','bolt','nut'],
  'Weather': ['sunny','cloudy','rainy','snowy','windy','stormy','foggy','humid','dry','hot','cold','freezing','warm','cool','thunder','lightning','hail','sleet','drizzle','mist'],
  'Emotions': ['happy','sad','angry','excited','nervous','calm','surprised','confused','proud','embarrassed','jealous','grateful','worried','relaxed','frustrated','content','anxious','joyful','disappointed','hopeful']
};
